spring.application.name=demo

# H2 콘솔(웹 화면) 접속 허용 스위치 ON
spring.h2.console.enabled=true

# 데이터베이스 이름과 접속 정보 설정
spring.datasource.url=jdbc:h2:file:./data/economydb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driverClassName=org.h2.Driver

# 우리가 짠 Java 코드를 보고 자동으로 테이블을 만들어주는 마법의 스위치
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.h2.console.settings.web-allow-others=true
# 서버가 모든 외부 IP의 접속을 허용하도록 강제 개방
server.address=0.0.0.0
# 가상 환경(Codespaces)에서 URL 경로가 꼬이지 않도록 설정
server.forward-headers-strategy=native